added deepCopyArrayOfObjects and unit-tests
IBM/lazy-z pull request #6
Opened 2023-09-19 17:50 UTC by Pseusco

added function which makes a deep copy of an array of objects

2023-09-19 18:05 UTC, jvallexm approved these changes

2023-09-20 13:03 UTC, jvallexm requested changes

2023-09-20 13:03 UTC, jvallexm commented on lib/arrays.js
> +  let newArr = []
need param check here to make sure is array of object. you can use `arrTypeCheck` iirc

2023-09-21 13:34 UTC, terechc approved these changes

2023-09-21 13:37 UTC, merged